### ISSUE TITLE
Cannot use /search or /random

### ISSUE THREAD

**Issue by Elyld** [idio-sync/romm-comm#11]
Every time after running either command in discord, it says that "an error occured while processing your request".

Checking the logs, I get this error every time.

2024-11-27 12:52:41,229 - cogs.search - ERROR - Error in select callback: 400 Bad Request (error code: 50035): Invalid Form Body
In components.1.components.0.url: Scheme "no website configured/api/roms/1560/content/crazy%20taxi%20%28usa%29.zip" is not supported. Scheme must be one of ('http', 'https', 'discord'). Not a well formed URL.
2024-11-27 12:52:41,229 - cogs.search - ERROR - Error in select callback: 400 Bad Request (error code: 50035): Invalid Form Body
In components.1.components.0.url: Scheme "no website configured/api/roms/1560/content/crazy%20taxi%20%28usa%29.zip" is not supported. Scheme must be one of ('http', 'https', 'discord'). Not a well formed URL.

**Comment by idio-sync** [comment]
It's trying to create a link to the rom through Romm on your server. Set the "domain" variable to a domain you own and have Romm pointed at or just the local LAN ip if you don't have it exposed publicly.
