### ISSUE TITLE
Firmware fetch returns error

### ISSUE THREAD

**Issue by noahtrr** [idio-sync/romm-comm#13]
The bot itself does work very well the only problem I have encountered is when attempting to fetch the firmware via discord.

File naming: [BIOS] Nintendo DS (World).zip

Working Dir location of bios file: /home/ubuntu/romm/library/bios/nds

```
romm-sync  | 2024-12-08 19:37:53,816 - romm_bot - INFO - Fetched fresh data for firmware?platform_id=1
romm-sync  | 2024-12-08 19:37:53,816 - cogs.search - ERROR - Error in firmware command: 'bios'
romm-sync  | 2024-12-08 19:37:53,816 - cogs.search - ERROR - Error in firmware command: 'bios'
```

**Comment by idio-sync** [comment]
Hmm I'll look into this. It's working fine for me, I'll see if I can reproduce the error somehow. 

![Screenshot_20241208-144811.png](https://github.com/user-attachments/assets/b8b04339-13ec-44b4-ba38-bec6024c58f2)

**Comment by noahtrr** [comment]
Well thanks, any way I can help? PS: Does it even matter how I name the BIOS zip files?/How or rather where I store them?

**Comment by idio-sync** [comment]
It shouldn't matter, it pulls from the RomM firmware database entry. I'll let you know if you can test anything though!

**Comment by idio-sync** [comment]
> Well thanks, any way I can help? PS: Does it even matter how I name the BIOS zip files?/How or rather where I store them?

It looks like this may be a cache error, can you try running the "/refresh" command and the running a firmware search? Also, just to confirm, you are able to see your firmware file in Romm itself?

**Comment by noahtrr** [comment]
Did a manual refresh, called for the firmware. Still returned an error.

![image](https://github.com/user-attachments/assets/e692ac7a-9476-4ea5-a1af-1a33075bb347)
![image](https://github.com/user-attachments/assets/da2a0cf4-30c6-4862-9032-ef1ceb1f8c0b)

**Comment by idio-sync** [comment]
I'm going to add some debug logging to the firmware command when I get a chance, in the meantime can you try it for a different platform, preferably one with more than one firmware file present?

**Comment by noahtrr** [comment]
I've just pulled the latest image, the firmware command returns the firmware without errors anymore.
