### ISSUE TITLE
docker issues - new download button

### ISSUE THREAD

**Issue by Salpertio** [idio-sync/romm-comm#9]
unraid - latest distribution of romm-comm 

as follows. 

start container
bot is logged in 
cogs loaded, commands available. bot is responsive in discord. 
"api data is successfully updated"

on discord. /search platform xbox game: tricky
(api is connected,  detailed info appears, box art etc.)

press button to go to the website (i am logged in to romm)
![Screenshot_2024-11-16_16-30-18](https://github.com/user-attachments/assets/776fd12f-5d64-41c9-85d8-84ad36250ce0)

**Comment by idio-sync** [comment]
Are you logged in to both the local and domain instance of Romm? I had issues with Romm not recognizing my account If I was logged in to both in the same browser session, I used one browser for local and one for my domain, and it seems to be okay. Set DISABLE_DOWNLOAD_ENDPOINT_AUTH=true to your RomM environment variables if you want to get around this completely.

**Comment by Salpertio** [comment]
seems mozilla was the culprit. 
moved to another browser and all is swell again. 

before we close. setting the role variable will initiate users to have accounts made in romm? or was that a module that's disabled because romm does not allow creating users through the api as of yet?

**Comment by idio-sync** [comment]
> seems mozilla was the culprit. moved to another browser and all is swell again.
> 
> before we close. setting the role variable will make it so users with said role will have accounts made in romm? or was that a module that's disabled because romm does not allow creating users through the api as of yet?

I'm still working on it, I need to debug the user creation a bit and I really don't want to push it out without being as close to 100% as I can.

**Comment by Salpertio** [comment]
understood. thank you.
